package cn.yinsheng.blog.rag.intent;

public enum IntentType {
  GREETING,
  SELF_INTRO,
  CAPABILITY_QUERY,
  BLOG_QA,
  BLOG_SEARCH,
  BLOG_SUMMARY,
  BLOG_RECOMMEND,
  BLOG_NAVIGATION,
  WEATHER_QUERY,
  JOKE,
  CALCULATOR,
  UNIT_CONVERT,
  DATETIME_QUERY,
  TIMESTAMP_CONVERT,
  URL_CODEC,
  BASE64_CODEC,
  TEXT_TRANSLATE,
  TEXT_POLISH,
  TEXT_SUMMARY,
  GENERAL_TECH_QA,
  SMALL_TALK,
  CLARIFICATION,
  UNSAFE_OR_FORBIDDEN,
  UNKNOWN
}
